package com.github.gekomad.regexcollection.js

import scala.scalajs.js.annotation._
import com.github.gekomad.regexcollection._

@JSExportTopLevel("Validator")
object ValidatorJS {

  import com.github.gekomad.regexcollection.Validate._

  @JSExport def validateTime24(s: String): Option[String]             = validate[Time24](s)
  @JSExport def validateApacheError(s: String): Option[String]        = validate[ApacheError](s)
  @JSExport def validateAsciiString(s: String): Option[String]        = validate[AsciiString](s)
  @JSExport def validateAZString(s: String): Option[String]           = validate[AZString](s)
  @JSExport def validateBitcoinAdd(s: String): Option[String]         = validate[BitcoinAdd](s)
  @JSExport def validateCelsius(s: String): Option[String]            = validate[Celsius](s)
  @JSExport def validateComments(s: String): Option[String]           = validate[Comments](s)
  @JSExport def validateCoordinate(s: String): Option[String]         = validate[Coordinate](s)
  @JSExport def validateCoordinate1(s: String): Option[String]        = validate[Coordinate1](s)
  @JSExport def validateCoordinate2(s: String): Option[String]        = validate[Coordinate2](s)
  @JSExport def validateCreditCardVisa(s: String): Option[String]     = validate[CreditCardVisa](s)
  @JSExport def validateCron(s: String): Option[String]               = validate[Cron](s)
  @JSExport def validateDMY(s: String): Option[String]                = validate[DMY](s)
  @JSExport def validateDMY2(s: String): Option[String]               = validate[DMY2](s)
  @JSExport def validateDMY3(s: String): Option[String]               = validate[DMY3](s)
  @JSExport def validateDMY4(s: String): Option[String]               = validate[DMY4](s)
  @JSExport def validateEmail(s: String): Option[String]              = validate[Email](s)
  @JSExport def validateEmail1(s: String): Option[String]             = validate[Email1](s)
  @JSExport def validateEmailSimple(s: String): Option[String]        = validate[EmailSimple](s)
  @JSExport def validateEurCurrency(s: String): Option[String]        = validate[EurCurrency](s)
  @JSExport def validateFacebook(s: String): Option[String]           = validate[Facebook](s)
  @JSExport def validateFahrenheit(s: String): Option[String]         = validate[Fahrenheit](s)
  @JSExport def validateGermanStreet(s: String): Option[String]       = validate[GermanStreet](s)
  @JSExport def validateHEX(s: String): Option[String]                = validate[HEX](s)
  @JSExport def validateIP(s: String): Option[String]                 = validate[IP](s)
  @JSExport def validateIP_6(s: String): Option[String]               = validate[IP_6](s)
  @JSExport def validateItalianFiscalCode(s: String): Option[String]  = validate[ItalianFiscalCode](s)
  @JSExport def validateItalianIban(s: String): Option[String]        = validate[ItalianIban](s)
  @JSExport def validateItalianMobilePhone(s: String): Option[String] = validate[ItalianMobilePhone](s)
  @JSExport def validateItalianPhone(s: String): Option[String]       = validate[ItalianPhone](s)
  @JSExport def validateItalianVAT(s: String): Option[String]         = validate[ItalianVAT](s)
  @JSExport def validateItalianZipCode(s: String): Option[String]     = validate[ItalianZipCode](s)
  @JSExport def validateMACAddress(s: String): Option[String]         = validate[MACAddress](s)
  @JSExport def validateMD5(s: String): Option[String]                = validate[MD5](s)
  @JSExport def validateMDY(s: String): Option[String]                = validate[MDY](s)
  @JSExport def validateMDY2(s: String): Option[String]               = validate[MDY2](s)
  @JSExport def validateMDY3(s: String): Option[String]               = validate[MDY3](s)
  @JSExport def validateMDY4(s: String): Option[String]               = validate[MDY4](s)
  @JSExport def validateNotASCII(s: String): Option[String]           = validate[NotASCII](s)
  @JSExport def validateNumber1(s: String): Option[String]            = validate[Number1](s)
  @JSExport def validatePercentage(s: String): Option[String]         = validate[Percentage](s)
  @JSExport def validateScientific(s: String): Option[String]         = validate[Scientific](s)
  @JSExport def validateSHA1(s: String): Option[String]               = validate[SHA1](s)
  @JSExport def validateSHA256(s: String): Option[String]             = validate[SHA256](s)
  @JSExport def validateSigned(s: String): Option[String]             = validate[Signed](s)
  @JSExport def validateSingleChar(s: String): Option[String]         = validate[SingleChar](s)
  @JSExport def validateSingleNumber(s: String): Option[String]       = validate[SingleNumber](s)
  @JSExport def validateStringAndNumber(s: String): Option[String]    = validate[StringAndNumber](s)
  @JSExport def validateTwitter(s: String): Option[String]            = validate[Twitter](s)
  @JSExport def validateUnsigned32(s: String): Option[String]         = validate[Unsigned32](s)
  @JSExport def validateURL(s: String): Option[String]                = validate[URL](s)
  @JSExport def validateUSphoneNumber(s: String): Option[String]      = validate[USphoneNumber](s)
  @JSExport def validateUsdCurrency(s: String): Option[String]        = validate[UsdCurrency](s)
  @JSExport def validateUSstates(s: String): Option[String]           = validate[USstates](s)
  @JSExport def validateUSstates1(s: String): Option[String]          = validate[USstates1](s)
  @JSExport def validateUSstreetNumber(s: String): Option[String]     = validate[USstreetNumber](s)
  @JSExport def validateUSstreets(s: String): Option[String]          = validate[USstreets](s)
  @JSExport def validateUSZipCode(s: String): Option[String]          = validate[USZipCode](s)
  @JSExport def validateUUID(s: String): Option[String]               = validate[UUID](s)
  @JSExport def validateYenCurrency(s: String): Option[String]        = validate[YenCurrency](s)
  @JSExport def validateYoutube(s: String): Option[String]            = validate[Youtube](s)

}

@JSExportTopLevel("Find")
object FindJS {
  import com.github.gekomad.regexcollection.Validate.findAll

  @JSExport def findAllTime24(s: String): List[String]             = findAll[Time24](s)
  @JSExport def findAllApacheError(s: String): List[String]        = findAll[ApacheError](s)
  @JSExport def findAllAsciiString(s: String): List[String]        = findAll[AsciiString](s)
  @JSExport def findAllAZString(s: String): List[String]           = findAll[AZString](s)
  @JSExport def findAllBitcoinAdd(s: String): List[String]         = findAll[BitcoinAdd](s)
  @JSExport def findAllCelsius(s: String): List[String]            = findAll[Celsius](s)
  @JSExport def findAllComments(s: String): List[String]           = findAll[Comments](s)
  @JSExport def findAllCoordinate(s: String): List[String]         = findAll[Coordinate](s)
  @JSExport def findAllCoordinate1(s: String): List[String]        = findAll[Coordinate1](s)
  @JSExport def findAllCoordinate2(s: String): List[String]        = findAll[Coordinate2](s)
  @JSExport def findAllCreditCardVisa(s: String): List[String]     = findAll[CreditCardVisa](s)
  @JSExport def findAllCron(s: String): List[String]               = findAll[Cron](s)
  @JSExport def findAllDMY(s: String): List[String]                = findAll[DMY](s)
  @JSExport def findAllDMY2(s: String): List[String]               = findAll[DMY2](s)
  @JSExport def findAllDMY3(s: String): List[String]               = findAll[DMY3](s)
  @JSExport def findAllDMY4(s: String): List[String]               = findAll[DMY4](s)
  @JSExport def findAllEmail(s: String): List[String]              = findAll[Email](s)
  @JSExport def findAllEmail1(s: String): List[String]             = findAll[Email1](s)
  @JSExport def findAllEmailSimple(s: String): List[String]        = findAll[EmailSimple](s)
  @JSExport def findAllEurCurrency(s: String): List[String]        = findAll[EurCurrency](s)
  @JSExport def findAllFacebook(s: String): List[String]           = findAll[Facebook](s)
  @JSExport def findAllFahrenheit(s: String): List[String]         = findAll[Fahrenheit](s)
  @JSExport def findAllGermanStreet(s: String): List[String]       = findAll[GermanStreet](s)
  @JSExport def findAllHEX(s: String): List[String]                = findAll[HEX](s)
  @JSExport def findAllIP(s: String): List[String]                 = findAll[IP](s)
  @JSExport def findAllIP_6(s: String): List[String]               = findAll[IP_6](s)
  @JSExport def findAllItalianFiscalCode(s: String): List[String]  = findAll[ItalianFiscalCode](s)
  @JSExport def findAllItalianIban(s: String): List[String]        = findAll[ItalianIban](s)
  @JSExport def findAllItalianMobilePhone(s: String): List[String] = findAll[ItalianMobilePhone](s)
  @JSExport def findAllItalianPhone(s: String): List[String]       = findAll[ItalianPhone](s)
  @JSExport def findAllItalianVAT(s: String): List[String]         = findAll[ItalianVAT](s)
  @JSExport def findAllItalianZipCode(s: String): List[String]     = findAll[ItalianZipCode](s)
  @JSExport def findAllMACAddress(s: String): List[String]         = findAll[MACAddress](s)
  @JSExport def findAllMD5(s: String): List[String]                = findAll[MD5](s)
  @JSExport def findAllMDY(s: String): List[String]                = findAll[MDY](s)
  @JSExport def findAllMDY2(s: String): List[String]               = findAll[MDY2](s)
  @JSExport def findAllMDY3(s: String): List[String]               = findAll[MDY3](s)
  @JSExport def findAllMDY4(s: String): List[String]               = findAll[MDY4](s)
  @JSExport def findAllNotASCII(s: String): List[String]           = findAll[NotASCII](s)
  @JSExport def findAllNumber1(s: String): List[String]            = findAll[Number1](s)
  @JSExport def findAllPercentage(s: String): List[String]         = findAll[Percentage](s)
  @JSExport def findAllScientific(s: String): List[String]         = findAll[Scientific](s)
  @JSExport def findAllSHA1(s: String): List[String]               = findAll[SHA1](s)
  @JSExport def findAllSHA256(s: String): List[String]             = findAll[SHA256](s)
  @JSExport def findAllSigned(s: String): List[String]             = findAll[Signed](s)
  @JSExport def findAllSingleChar(s: String): List[String]         = findAll[SingleChar](s)
  @JSExport def findAllSingleNumber(s: String): List[String]       = findAll[SingleNumber](s)
  @JSExport def findAllStringAndNumber(s: String): List[String]    = findAll[StringAndNumber](s)
  @JSExport def findAllTwitter(s: String): List[String]            = findAll[Twitter](s)
  @JSExport def findAllUnsigned32(s: String): List[String]         = findAll[Unsigned32](s)
  @JSExport def findAllURL(s: String): List[String]                = findAll[URL](s)
  @JSExport def findAllUSphoneNumber(s: String): List[String]      = findAll[USphoneNumber](s)
  @JSExport def findAllUsdCurrency(s: String): List[String]        = findAll[UsdCurrency](s)
  @JSExport def findAllUSstates(s: String): List[String]           = findAll[USstates](s)
  @JSExport def findAllUSstates1(s: String): List[String]          = findAll[USstates1](s)
  @JSExport def findAllUSstreetNumber(s: String): List[String]     = findAll[USstreetNumber](s)
  @JSExport def findAllUSstreets(s: String): List[String]          = findAll[USstreets](s)
  @JSExport def findAllUSZipCode(s: String): List[String]          = findAll[USZipCode](s)
  @JSExport def findAllUUID(s: String): List[String]               = findAll[UUID](s)
  @JSExport def findAllYenCurrency(s: String): List[String]        = findAll[YenCurrency](s)
  @JSExport def findAllYoutube(s: String): List[String]            = findAll[Youtube](s)

}

@JSExportTopLevel("FindFirst")
object FindFirstJS {
  import com.github.gekomad.regexcollection.Validate.findFirst

  @JSExport def findFirstTime24(s: String): Option[String]             = findFirst[Time24](s)
  @JSExport def findFirstApacheError(s: String): Option[String]        = findFirst[ApacheError](s)
  @JSExport def findFirstAsciiString(s: String): Option[String]        = findFirst[AsciiString](s)
  @JSExport def findFirstAZString(s: String): Option[String]           = findFirst[AZString](s)
  @JSExport def findFirstBitcoinAdd(s: String): Option[String]         = findFirst[BitcoinAdd](s)
  @JSExport def findFirstCelsius(s: String): Option[String]            = findFirst[Celsius](s)
  @JSExport def findFirstComments(s: String): Option[String]           = findFirst[Comments](s)
  @JSExport def findFirstCoordinate(s: String): Option[String]         = findFirst[Coordinate](s)
  @JSExport def findFirstCoordinate1(s: String): Option[String]        = findFirst[Coordinate1](s)
  @JSExport def findFirstCoordinate2(s: String): Option[String]        = findFirst[Coordinate2](s)
  @JSExport def findFirstCreditCardVisa(s: String): Option[String]     = findFirst[CreditCardVisa](s)
  @JSExport def findFirstCron(s: String): Option[String]               = findFirst[Cron](s)
  @JSExport def findFirstDMY(s: String): Option[String]                = findFirst[DMY](s)
  @JSExport def findFirstDMY2(s: String): Option[String]               = findFirst[DMY2](s)
  @JSExport def findFirstDMY3(s: String): Option[String]               = findFirst[DMY3](s)
  @JSExport def findFirstDMY4(s: String): Option[String]               = findFirst[DMY4](s)
  @JSExport def findFirstEmail(s: String): Option[String]              = findFirst[Email](s)
  @JSExport def findFirstEmail1(s: String): Option[String]             = findFirst[Email1](s)
  @JSExport def findFirstEmailSimple(s: String): Option[String]        = findFirst[EmailSimple](s)
  @JSExport def findFirstEurCurrency(s: String): Option[String]        = findFirst[EurCurrency](s)
  @JSExport def findFirstFacebook(s: String): Option[String]           = findFirst[Facebook](s)
  @JSExport def findFirstFahrenheit(s: String): Option[String]         = findFirst[Fahrenheit](s)
  @JSExport def findFirstGermanStreet(s: String): Option[String]       = findFirst[GermanStreet](s)
  @JSExport def findFirstHEX(s: String): Option[String]                = findFirst[HEX](s)
  @JSExport def findFirstIP(s: String): Option[String]                 = findFirst[IP](s)
  @JSExport def findFirstIP_6(s: String): Option[String]               = findFirst[IP_6](s)
  @JSExport def findFirstItalianFiscalCode(s: String): Option[String]  = findFirst[ItalianFiscalCode](s)
  @JSExport def findFirstItalianIban(s: String): Option[String]        = findFirst[ItalianIban](s)
  @JSExport def findFirstItalianMobilePhone(s: String): Option[String] = findFirst[ItalianMobilePhone](s)
  @JSExport def findFirstItalianPhone(s: String): Option[String]       = findFirst[ItalianPhone](s)
  @JSExport def findFirstItalianVAT(s: String): Option[String]         = findFirst[ItalianVAT](s)
  @JSExport def findFirstItalianZipCode(s: String): Option[String]     = findFirst[ItalianZipCode](s)
  @JSExport def findFirstMACAddress(s: String): Option[String]         = findFirst[MACAddress](s)
  @JSExport def findFirstMD5(s: String): Option[String]                = findFirst[MD5](s)
  @JSExport def findFirstMDY(s: String): Option[String]                = findFirst[MDY](s)
  @JSExport def findFirstMDY2(s: String): Option[String]               = findFirst[MDY2](s)
  @JSExport def findFirstMDY3(s: String): Option[String]               = findFirst[MDY3](s)
  @JSExport def findFirstMDY4(s: String): Option[String]               = findFirst[MDY4](s)
  @JSExport def findFirstNotASCII(s: String): Option[String]           = findFirst[NotASCII](s)
  @JSExport def findFirstNumber1(s: String): Option[String]            = findFirst[Number1](s)
  @JSExport def findFirstPercentage(s: String): Option[String]         = findFirst[Percentage](s)
  @JSExport def findFirstScientific(s: String): Option[String]         = findFirst[Scientific](s)
  @JSExport def findFirstSHA1(s: String): Option[String]               = findFirst[SHA1](s)
  @JSExport def findFirstSHA256(s: String): Option[String]             = findFirst[SHA256](s)
  @JSExport def findFirstSigned(s: String): Option[String]             = findFirst[Signed](s)
  @JSExport def findFirstSingleChar(s: String): Option[String]         = findFirst[SingleChar](s)
  @JSExport def findFirstSingleNumber(s: String): Option[String]       = findFirst[SingleNumber](s)
  @JSExport def findFirstStringAndNumber(s: String): Option[String]    = findFirst[StringAndNumber](s)
  @JSExport def findFirstTwitter(s: String): Option[String]            = findFirst[Twitter](s)
  @JSExport def findFirstUnsigned32(s: String): Option[String]         = findFirst[Unsigned32](s)
  @JSExport def findFirstURL(s: String): Option[String]                = findFirst[URL](s)
  @JSExport def findFirstUSphoneNumber(s: String): Option[String]      = findFirst[USphoneNumber](s)
  @JSExport def findFirstUsdCurrency(s: String): Option[String]        = findFirst[UsdCurrency](s)
  @JSExport def findFirstUSstates(s: String): Option[String]           = findFirst[USstates](s)
  @JSExport def findFirstUSstates1(s: String): Option[String]          = findFirst[USstates1](s)
  @JSExport def findFirstUSstreetNumber(s: String): Option[String]     = findFirst[USstreetNumber](s)
  @JSExport def findFirstUSstreets(s: String): Option[String]          = findFirst[USstreets](s)
  @JSExport def findFirstUSZipCode(s: String): Option[String]          = findFirst[USZipCode](s)
  @JSExport def findFirstUUID(s: String): Option[String]               = findFirst[UUID](s)
  @JSExport def findFirstYenCurrency(s: String): Option[String]        = findFirst[YenCurrency](s)
  @JSExport def findFirstYoutube(s: String): Option[String]            = findFirst[Youtube](s)

}
